"""add xpath column to manual_task_dom_information table

Revision ID: add_xpath_to_manual_dom_info
Revises: add_manual_task_dom_info_table
Create Date: 2025-09-16 12:20:00.000000+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'add_xpath_to_manual_dom_info'
down_revision: Union[str, None] = 'add_manual_task_dom_info_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manual_task_dom_information', sa.Column('xpath', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manual_task_dom_information', 'xpath')
    # ### end Alembic commands ###
