"""add manual_task_dom_info_table

Revision ID: add_manual_task_dom_info_table
Revises: add_exta_info_to_task_runs
Create Date: 2025-09-16 12:19:00.000000+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'add_manual_task_dom_info_table'
down_revision: Union[str, None] = 'add_exta_info_to_task_runs'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manual_task_dom_information',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('tag', sa.VARCHAR(), nullable=False),
    sa.Column('input_type', sa.VARCHAR(), nullable=True),
    sa.Column('is_mandatory', sa.BOOLEAN(), nullable=False),
    sa.Column('placeholder', sa.VARCHAR(), nullable=True),
    sa.Column('value', sa.TEXT(), nullable=True),
    sa.Column('user_email', sa.VARCHAR(), nullable=True),
    sa.Column('job_link', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_manual_task_dom_user_email'), 'manual_task_dom_information', ['user_email'], unique=False)
    op.create_index(op.f('idx_manual_task_dom_job_link'), 'manual_task_dom_information', ['job_link'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_manual_task_dom_job_link'), table_name='manual_task_dom_information')
    op.drop_index(op.f('idx_manual_task_dom_user_email'), table_name='manual_task_dom_information')
    op.drop_table('manual_task_dom_information')
    # ### end Alembic commands ###
