"""add user_email and workflow_run_id to task_runs

Revision ID: add_exta_info_to_task_runs
Revises: b7dbf5cf75a6
Create Date: 2025-08-25 10:12:00.000000+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'add_exta_info_to_task_runs'
down_revision: Union[str, None] = 'b7dbf5cf75a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_runs', sa.Column('user_email', sa.VARCHAR(), nullable=True))
    op.add_column('task_runs', sa.Column('workflow_run_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'task_runs', 'workflow_runs', ['workflow_run_id'], ['workflow_run_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_runs', type_='foreignkey')
    op.drop_column('task_runs', 'workflow_run_id')
    op.drop_column('task_runs', 'user_email')
    # ### end Alembic commands ### 