"""dom_info_task_table added

Revision ID: b7dbf5cf75a6
Revises: 2e997076a3aa
Create Date: 2025-08-21 09:17:37.583626+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7dbf5cf75a6'
down_revision: Union[str, None] = '2e997076a3aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_dom_information',
    sa.Column('dom_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('xpath', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('input_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_mandatory', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('placeholder', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], name=op.f('fk_task_dom_information_task'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dom_id', name=op.f('task_dom_information_pkey'))
    )
    op.create_index(op.f('idx_task_dom_task_id'), 'task_dom_information', ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_task_dom_task_id'), table_name='task_dom_information')
    op.drop_table('task_dom_information')
    # ### end Alembic commands ###
